export const plyrID = 'plyr_player__section';
export const i18nOptions = {
  restart: 'Restart',
  rewind: 'Rewind {seektime}s',
  play: 'Play',
  pause: 'Pause',
  fastForward: 'Forward {seektime}s',
  seek: 'Seek',
  seekLabel: '{currentTime} of {duration}',
  played: 'Played',
  buffered: 'Buffered',
  currentTime: 'Current time',
  duration: 'Duration',
  volume: 'Volume',
  mute: 'Mute',
  unmute: 'Unmute',
  enableCaptions: 'Enable captions',
  disableCaptions: 'Disable captions',
  download: 'Download',
  enterFullscreen: 'Enter fullscreen',
  exitFullscreen: 'Exit fullscreen',
  frameTitle: 'Player for {title}',
  captions: 'Captions',
  settings: 'Settings',
  menuBack: 'Go back to previous menu',
  speed: 'Speed',
  normal: 'Normal',
  quality: 'Quality',
  loop: 'Loop',
};

export const controlOptions = (controls: string[] = []) => [
  'play',
  'play-large',
  'progress',
  'captions',
  'pip',
  'airplay',
  'current-time',
  'duration',
  'mute',
  'volume',
  'settings',
  'fullscreen',
  ...controls,
];

export const settingOptions = ['captions', 'quality', 'speed', 'loop'];
